use_frameworks!

platform :ios, '11.0'

target 'ClusteredFiltersKit_Example' do
  pod 'ClusteredFiltersKit', :path => '../'

  target 'ClusteredFiltersKit_Tests' do
    inherit! :search_paths

    
  end
end
